### ISSUE TITLE
no issues just want to thank you

### ISSUE THREAD

**Issue by husenlovedisney** [iamspark1e/netlify-cms-widget-simplemde#3]
just wanted to say thank you😀 but is it possible to add a shortcode into the body of simplemde, thanks

**Comment by iamspark1e** [comment]
I published a new version. The "Code" button has been re-add to the toolbar.
![image](https://github.com/iamspark1e/netlify-cms-widget-simplemde/assets/29349655/687ec3c4-6dd3-4d88-8085-f20c94d26587)

(I'm sorry, English is not my native language. I'm not sure if I understood correctly. If not, please let me know, and I will provide further change. 😃 )

**Comment by husenlovedisney** [comment]
it looks really nice adding a code button, but I mean registering block level components for Simplemde's Markdown editor
![png_20230516_021751_0000](https://github.com/iamspark1e/netlify-cms-widget-simplemde/assets/122751959/83a7075c-2837-43a1-9713-7514e86075b1)
Kamu bisa lihat [disini](https://decapcms.org/docs/hugo/#using-hugo-shortcodes-in-the-markdown-editor)

**Comment by iamspark1e** [comment]
Thank you, I found I missed this part of the official document.

As the docs say, shortcodes can be registered by `CMS.registerEditorComponent`, so if I didn't misunderstand, you can add some code to fulfill your needs.

Here is an example,

```javascript
// You need to register widget first, as README.
CMS.registerWidget("simplemde", SimpleMDEControl, SimpleMDEPreview);

CMS.registerEditorComponent({
  id: "shortcode-simplemde",
  label: "Shortcode SimpleMDE",
  fields: [{
    name: "yet-another-markdown-content",
    label: "Yet Another Markdown Content",
    widget: "simplemde" // use the same name of the widget registered.
  }],
  pattern: /{{< simplemde ([a-zA-Z0-9]+) >}}/, // this pattern may be not correct, change this to fit your condition.
  fromBlock: function (match) {
    return {
      "yet-another-markdown-content": match[1],
    };
  },
  toBlock: function (obj) {
    return `{{< simplemde ${obj["yet-another-markdown-content"]} >}}`;
  },
  toPreview: function (obj) {
    return `{{< simplemde ${obj["yet-another-markdown-content"]} >}}`;
  },
});
```

When I tested this kind of usage, I found there might be conflict between the original Markdown widget and my replacement widget. I'm not sure this could solve your problem.

**Comment by husenlovedisney** [comment]
I've tried that and maybe it doesn't work, but I'm very grateful, I'll close this issue😃🙏
